### ISSUE TITLE
Fail to reappear the mIoU reported in the paper.

### ISSUE THREAD

**Issue by Pengz98** [ZhaochongAn/COSeg#1]
Hi! Thank you for your excellent work in few shot segmentation.
I have tried to reappear the final result following the guideline, but didn't achieve the mIoU value reported in the paper (48.1 for 1-way 1-shot in S3DIS).
To be specific, the mIoU value reaches the maximum (45.38) in Epoch 13, and remains around 40 till the Epoch 100.
I am not sure if there is any detail I didn't aware of.
It will be helpful if you could offer the well-trained weight of the few-shot training phase.

**Comment by ZhaochongAn** [comment]
Hello! Thank you for the interests in our work. The training process does have some variance. And sometimes it could happen that the best-performing model may be obtained from the early checkpoints. I have released the model weights. Hope it can be helpful.
