### ISSUE TITLE
How many GPUs the author used on the computer

### ISSUE THREAD

**Issue by zmyDggs** [ZhaochongAn/COSeg#11]
How many GPUs the author used on the computer
I'm about to start multiple processes when an error occurs
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in

**Comment by ZhaochongAn** [comment]
Hi, I am using 4 gpus for the training. The issue seems related to your wrong installation of torch https://discuss.pytorch.org/t/runtimeerror-distributed-package-doesnt-have-nccl-built-in/176744.
