### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_points_kernels.points_cuda'

### ISSUE THREAD

**Issue by Lzy-dot** [ZhaochongAn/COSeg#3]
I have installed all the dependencies with the same version as you mentioned and I have finished processing dependencies for pointops2==0.0.0. But I still have the problem 'ModuleNotFoundError: No module named 'torch_points_kernels.points_cuda'.

**Comment by ZhaochongAn** [comment]
Hello, it appears that there might be an issue with the installation of "torch_points_kernels." Could you run "import torch_points_kernels" in your environment to check if the package imports successfully?
