### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by yihang-xdu** [ZhaochongAn/COSeg#4]
Dear Authors,
Thanks for your great work! Could you please tell me how long it takes for Backbone pretraining and Few-shot training?

**Comment by ZhaochongAn** [comment]
Hello, thank you for your interest in our work! 

The Backbone pretraining time varies with the training set: approximately 27 hours for both splits 0 and 1 of the S3DIS dataset, and 31 hours on split 0 and 27 hours on split 1 for the ScanNet dataset.

For few-shot training, the duration depends on the task. For example, a 1-way 1-shot task on S3DIS typically takes about 18 hours. It's worth noting that optimal performance is often achieved midway through training, which provides ample opportunities to fine-tune the training setup for greater time efficiency.
