### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by AmingWu** [ZhaochongAn/COSeg#5]
Dear Authors,

I have run the evaluation code with vis 1 successfully. However, I do not know how to obtain the visualization results shown in your paper. Could you tell me how to achieve it?

Thanks.

**Comment by Lzy-dot** [comment]
I also have this question. Could the author please answer it? This will help us follow up on your work."

**Comment by AmingWu** [comment]
Thanks. If you update the code, could you tell me? Thanks.

**Comment by ZhaochongAn** [comment]
Hello, I have just released the visualization code and included instructions in the README for your reference. Hope it will help!
