### ISSUE TITLE
How is the ground-truth label transferred to dense point clouds?

### ISSUE THREAD

**Issue by kasteric** [ZhaochongAn/COSeg#6]
Hi, in the upsampling process, does the ground-truth label is set to be the original point that is localized in the same voxel, which is binary(0 or 1) ?

**Comment by ZhaochongAn** [comment]
Hello, the ground-truth labels maintain a 1-to-1 matching relationship with the points at that resolution. And we do not use groud-truth labels during unsampling process (which is non-learnable). Maybe referring to the specific part of the code could help clarify your questions.
