### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by AmingWu** [ZhaochongAn/COSeg#9]
Dear Authors,

When I run your new code, there exists an error:

![微信图片_20240626190853](https://github.com/ZhaochongAn/COSeg/assets/38445175/ea9733e1-3236-4965-9136-cda6bf4aa7a4)

Could you give me some advice? Thanks.

**Comment by ZhaochongAn** [comment]
Hi, it seems that the target class you specified might not be included in the test split. Could you share the exact commands you used to run the code?

**Comment by AmingWu** [comment]
This is the command:

python3 main_fs.py --config config/s3dis_COSeg_fs.yaml test True weight "/data1/zyh/COSeg/trained_model/model/model_last.pth" cvfold 0 train_gpu [0] vis_save_path ./vis forvis 1 data_root /data1/zyh/COSeg/datasets/S3DIS/blocks_bs1_s1/data target_class table

**Comment by ZhaochongAn** [comment]
Your command shows the issue I mentioned. You are using `cvfold 0` as the test split but have specified `target_class` as `table`, which is used for `cvfold 1`, not `0`. Therefore, the table index is not defined in the test split (`cvfold 0`).

**Comment by AmingWu** [comment]
Could you tell me the cvfold 0 owns concret categories?

**Comment by ZhaochongAn** [comment]
The concrete category divisions can be found in the dataset class definition: https://github.com/ZhaochongAn/COSeg/blob/75f39091b49ed73b2f06bcf68555986d5d75fa30/util/s3dis_fs.py#L53-L61.

**Comment by AmingWu** [comment]
Thanks. Since my device does not create window to display the results, could you tell me how to save the results to .ply?

**Comment by AmingWu** [comment]
Besides, the saved results contain pred.npy, query.npy, querylb.npy, sup.npy, and suplb.npy. Could you tell me their meaning? Which one is used for visualization?

**Comment by ZhaochongAn** [comment]
The visualization code uses all these saved results to show the whole few-shot episode. They are corresponding to query predictions, query data, query labels, support data, and support labels, respectively.

**Comment by AmingWu** [comment]
Thanks. If I can directly save these files to .ply, it will be convenient to perform visualization for me. Could you give me some advice? Thanks

**Comment by AmingWu** [comment]
![捕获](https://github.com/ZhaochongAn/COSeg/assets/38445175/e24805ec-babc-4068-84ab-aba8d799178d)
你好，这是可视化结果，如何才能获得论文上那种标注特定颜色的分割结果呢？

**Comment by ZhaochongAn** [comment]
Hi, our visualization code renders all the results one by one. If you follow the code, you will get all the results including the predictions. You could press 'q' to finish the current rendering window and continue to the next result automatically.

**Comment by lrnb12345** [comment]
> 您好，我们的可视化代码会逐一渲染所有结果。如果您按照代码操作，您将获得所有结果（包括预测）。您可以按“q”完成当前渲染窗口并自动继续下一个结果。

Hello, I visualized the query prediction results, but the entire scene is black. Why is this
![Uploading 屏幕截图 2024-08-18 145037.png…]()

**Comment by lrnb12345** [comment]
> ![捕获](https://private-user-images.githubusercontent.com/38445175/345255941-e24805ec-babc-4068-84ab-aba8d799178d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzAyNTEsIm5iZiI6MTcyNDEyOTk1MSwicGF0aCI6Ii8zODQ0NTE3NS8zNDUyNTU5NDEtZTI0ODA1ZWMtYmFiYy00MDY4LTg0YWItYWJhOGQ3OTkxNzhkLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA0NTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZTU0MGNhMTIzMDNkYmM3YjdkODYwODAxN2MwYmQxYjhiNzg5Y2IxNzkyNDQ2MTQwN2EwYzUxNTVkZDE1M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lOHKueP3u1li1Mc5SZNboOJ8hh3Mt1YgugB3BZLPwbs) 你好，这是可视化的结果，如何才能获得论文上那种特定颜色的分割结果呢？

Hello, may I ask if you have encountered a situation where the visualization of your prediction results is all black

**Comment by lrnb12345** [comment]
> ![捕获](https://private-user-images.githubusercontent.com/38445175/345255941-e24805ec-babc-4068-84ab-aba8d799178d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTEwOTcsIm5iZiI6MTcyNjIxMDc5NywicGF0aCI6Ii8zODQ0NTE3NS8zNDUyNTU5NDEtZTI0ODA1ZWMtYmFiYy00MDY4LTg0YWItYWJhOGQ3OTkxNzhkLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA2NTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZDY3N2FjNmRmN2RmMmZhOWViOTY1MmFmYzU1MjZiOTZhNzhlMTFhMzJhZTlkNWMxN2ViMDQ0ZDkyNjhkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IscRbso060n4c4g4OKoCIPG3DPu30WuxpSJa4fFRdw) 你好，这是可视化的结果，如何才能获得论文上那种特定颜色的分割结果呢？

Hello, have you successfully saved the result as ply and visualized it? How can I do it

**Comment by lixin-zhan** [comment]
> ![捕获](https://github.com/ZhaochongAn/COSeg/assets/38445175/e24805ec-babc-4068-84ab-aba8d799178d) 你好，这是可视化结果，如何才能获得论文上那种标注特定颜色的分割结果呢？

你好，请问如何实现整个场景的可视化，现在代码只能显示一个块

**Comment by gdggshaidbdj** [comment]
> > ![捕获](https://github.com/ZhaochongAn/COSeg/assets/38445175/e24805ec-babc-4068-84ab-aba8d799178d)你好，这是可视化结果，如何才能获得论文上那种标注特定颜色的分割结果呢？
> 
> 你好，请问如何实现整个场景的可视化，现在代码只能显示一个块

您好，请问您解决了吗，我也遇到了同样的问题
